In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!git branch aditya0335/DIC-Assignment1

fatal: Not a valid object name: 'master'.


Drive-bansaladitya0335@gmail.com

In [0]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
os.chdir('/content/drive/My Drive/DIC ASSIGNMENT 1')
data=pd.read_csv('data.csv')
features=data.iloc[:,0:48]
labels=data.iloc[:,48]
features_train,features_test,labels_train,labels_test=train_test_split(features,labels,test_size=0.2)

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report 
from sklearn import preprocessing
from sklearn.preprocessing import scale
from sklearn.preprocessing import MinMaxScaler
# features = preprocessing.normalize(features)
# features=scale(features)

In [0]:
features_train=np.asarray(features_train)
features_test=np.asarray(features_test)
labels_train=np.asarray(labels_train)
labels_test=np.asarray(labels_test)
print(features_test.shape)
print(features_train.shape)
# features_test_repeat=np.repeat(features_test,32764,0)
# print(features_test_repeat.shape)
row=features_train[:1,]
print(row.shape)
scaler = MinMaxScaler()
features_train=scaler.fit_transform(features_train)
features_test=scaler.transform(features_test)
# for row in features_test:
#   print(np.tile(row,reps=[32764,1])-features_train)
  
# features_train_repeat=np.tile(features_train,reps=)

(8192, 48)
(32764, 48)
(1, 48)


In [0]:
def KNN(X_train,X_test,Y_train):
  testresult=[]
  k_value=50
  b=0
  testresult_test=[]
  for row in X_test:
    distance=[]
    knn = []
    row=np.asarray(row)
    row=row.reshape(1,48)
    
    # distance=np.sqrt(np.sum(np.subtract(np.tile(row,reps=[32764,1]),X_train),axis=1),axis=1)
    distance=np.sqrt(np.sum(np.square((np.subtract(np.repeat(row,32764,0),X_train))),axis=1))
    distance=distance.reshape(32764,1)
    Y_train=Y_train.reshape(32764,1)
    distance_Y_train=np.concatenate((Y_train,distance),axis=1)
    distance_Y_train =  distance_Y_train[np.argsort(distance_Y_train[:, 1])]    
    knn = distance_Y_train[:k_value]
    knn=knn[:,0]
    knn=knn.astype(int)
    # print(np.bincount(knn).argmax())
    testresult_test=np.append(testresult_test,np.bincount(knn).argmax())
  return testresult_test
result=KNN(features_train,features_test,labels_train)


In [0]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
# knn = KNeighborsClassifier(n_neighbors=100)
# knn.fit(features_train,features_test )
# y_pred = knn.predict(labels_train)
# print(accuracy_score(labels_test,y_pred))
result=result.astype(int)
print(accuracy_score(labels_test,result))

0.9769287109375


In [0]:
data.describe
fetures_for_split=np.sqrt(np.size(data,1)) #7 features
index=np.arange(48)
random_sample=np.random.choice(index,size=fetures_for_split.astype(int),replace=True)
random_features=features_train[:,random_sample]
print(data.shape[0])
index_bootstrap=np.arange(data.shape[0])
print(index_bootstrap)
bootstrap_sample=np.random.choice(index_bootstrap,data.shape[0],replace=True)
print(bootstrap_sample)
bootstrap_data=data.values[bootstrap_sample,:]
print(bootstrap_data.shape)

40956
[    0     1     2 ... 40953 40954 40955]
[16029 11149 22342 ... 17089 21681 28501]
(40956, 49)


In [0]:
column=data.values[:,23]
mean=np.sum(column)/column.shape
print(mean)
print(np.percentile(column,10))
test=data.iloc[:,0:48]
print(np.percentile(test,10,axis=0).shape)

test=data.iloc[:,0:48]
split=[10,20,30,40,50,60,70,80,90]
for i in split:
  split_data=np.percentile(test,i,axis=0)
  c=0
  for column in data:
    a=data.values[:,c]<=split_data[c]
    print("fsf")
    a=a[[:,c],[:,-1]] #change
    size_a=size = float(len(a))
    score=0.0
    classes=np.arange(11)
    if(size_a==0):
      continue
    else:
      for class_val in classes:
        p = a[-1].count(class_val) / size
        score += p * p
  # weight the group score by its relative size
        gini += (1.0 - score) * (size / n_instances)
    score=0.0       
    b=data.values[:,c]>split_data[c]
    b=b[[:,c],[:,-1]]
    c+=1
    size_b=size = float(len(a))
    if(size_b==0):
      continue
    else:
      for class_val in classes:
        p = b[-1].count(class_val) / size
        score += p * p
        gini += (1.0 - score) * (size / n_instances)
      giniscore=np.append(giniscore,gini)
      giniscore=np.minimum(giniscore)
      final_gini=np.append(giniscore)
      final_gini_score=[np.minimum(final_gini),i]



SyntaxError: ignored

Deepesh

In [0]:
# -*- coding: utf-8 -*-
"""
Predicitve_Analytics.py
"""


def Accuracy(y_true,y_pred):
  size=y_true.size
  
    # """
    # :type y_true: numpy.ndarray
    # :type y_pred: numpy.ndarray
    # :rtype: float
    
    # """

In [0]:
array1=np.array([[4,4,4,3],[7,9,2,0]])
array2=np.array([[7],[8]])
array3=np.concatenate((array1, array2), axis=1)
print(array3)


[[4 4 4 3 7]
 [7 9 2 0 8]]


Pooja

In [0]:

def Recall(y_true,y_pred):
  labelsize=11
  size=y_true.size
  a=0
  b=0
  recall=0
  for i in range (labelsize):
    for j in range (size):
      if y_true[j]==i:
        a+=1
        if y_true[j]==y_pred[j]==i:
          b+=1
    recall+=b/a
  recall=recall/11
  return recall


final=Recall(labels_test,labels_test)
print(final)


    #  """
    # :type y_true: numpy.ndarray
    # :type y_pred: numpy.ndarray
    # :rtype: float
    # """



KeyError: ignored

Aditya

In [0]:
def Precision(y_true,y_pred):
  
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """


In [0]:
def WCSS(Clusters):
    """
    :Clusters List[numpy.ndarray]
    :rtype: float
    """

In [0]:
def ConfusionMatrix(y_true,y_pred):
    
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """ 
def sortSecond(val): 
    return val[1] 
ab=[]
bc=[]
cd=[]
ab.append((5,4))
ab.append((7,8))
ab.append((9,6))
ab.sort(key = sortSecond)
bc=ab[:2]
print(ab)
for k in bc:
  cd.append(k[0])
print(max(cd))
for row in features_test:
  print(np.linalg.norm(row-features_train))

Streaming output truncated to the last 5000 lines.
4775.379114105703
4687.959917717694
4198.70290535628
4305.0265724931705
4314.411415609765
4294.865525875041
4475.860069408181
4154.20718028363
4617.1015978495425
4179.071907620391
4158.024698895125
4470.982645257417
4620.179051903552
5897.485693793357
5350.406590409938
4129.320978284359
4558.485728609966
4387.030230427739
4677.806678835419
4369.018006788864
4248.62313821441
4253.596865260536
4178.513913186985
4073.384199421392
5964.005446436388
5156.076776294044
4451.707492897074
4827.205889342978
4220.015586666987
4165.004922569258
4447.698127992643
5434.34102223226
4265.052168657578
4243.086977769364
8921.890286885055
4315.090302859856
6311.236119448171
4301.434691907885
5135.947740814482
4314.527197958292
6350.972122056568
4327.387111930284
4545.781239369234
4208.62687088148
4506.683886077126
4174.810045359712
4480.543119377411
4549.887100498774
4183.608253606466
4449.732778514527
4316.511917996119
4303.640384506925
4565.32632864572

KeyboardInterrupt: ignored

Aditya

In [0]:
def sortSecond(val): 
    return val[1] 
def KNN(X_train,X_test,Y_train):
  testresult=[]
  k_value=5
  b=0
  for row in X_test:
    np.tile(row,reps=[32764,1])
    # print(b)
    b+=1
    distance=[]
    knn = []
    testresult_test=[]
    shape=Y_train.size
    a=0
    # for j in X_train:
    #         # eu_dist = euclideanDisatnce(row, j)
    #         # print(eu_dist)
    #         eu_dist = np.linalg.norm(row-j)
    #         # print(dist)
    #         # print(eu_dist)
    #         # eu_dist=np.sum((row - j) ** 2, axis=0)
    #         # print(eu_dist)
    #         # print(Y_train[a])
    #         # np.append(distance,(Y_train[a], eu_dist))
            
    #         # distance =  distance[np.argsort(distance[:, 1])]
    #         distance.append((Y_train[a], eu_dist))
    #         a+=1
    distance.append((Y_train, np.linalg.norm(row-X_train)))
    distance=np.asarray(distance)
    distance[distance[:,1].argsort()]
    # distance.sort(key = sortSecond)
    print(distance)
    # print(distance)
    knn = distance[:k_value]        
    for k in knn:
      testresult_test.append(k[0])
      # testresult_test.append(k[0])
    testresult_test=np.asarray(testresult_test)
    print(testresult_test)
    # print(testresult_test)
    # print(np.bincount(testresult_test).argmax())
    np.append(testresult_test,np.bincount(testresult_test).argmax())
  # np.append(testresult, np.bincount(testresult_test))
    # print(testresult)
  return testresult
        


    #  """
    # :type X_train: numpy.ndarray
    # :type X_test: numpy.ndarray
    # :type Y_train: numpy.ndarray
    
    # :rtype: numpy.ndarray
    # """
def euclideanDisatnce(y_true,y_pred):
  size=len(y_true)
  distance=0
  for i in range(size-1):
    distance+=(y_true[i]-y_pred[i])**2
  final=np.sqrt(distance)
  return final



In [0]:
y_pred=KNN(features_train,features_test,labels_train)

[[array([ 4, 10,  5, ..., 11,  2,  5]) 4393.671209050852]]
[[ 4 10  5 ... 11  2  5]]


ValueError: ignored

In [0]:
def RandomForest(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: numpy.ndarray
    """

Pooja

In [0]:
def PCA(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: numpy.ndarray
    """

Deepesh

In [0]:
def Kmeans(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: List[numpy.ndarray]
    """

In [0]:
def SklearnSupervisedLearning(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """

In [0]:
def SklearnVotingClassifier(X_train,Y_train,X_test):
    
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """


"""
Create your own custom functions for Matplotlib visualization of hyperparameter search. 
Make sure that plots are labeled and proper legends are used
"""